### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by LeonardSpencer** [revolist/vue3-datagrid#1]
Hi! Great work on this component. Will try it out the couple of weeks so I think you can aspect more issues-tickets from me with bugs or feature requests :). Is there a definition file present for Typescript?

**Comment by revolist** [comment]
The whole component RevoGrid built with typescript. I ou can have all type definitions from it.

Vue3-datagrid is extension for vue but it still has RevoGrid base inside. Take all necessary styles from there.

Don't hesitate to post issues/suggestions!

**Comment by LeonardSpencer** [comment]
I quess I then don't fully understand what I'm looking for. I have a vue3 project with typescript but I don't have strongtyping and I thought I need to include the definition file of it but I dont really understand how I do that.

**Comment by revolist** [comment]
@LeonardSpencer check it here:
https://github.com/revolist/vue3-datagrid/blob/master/public/App.vue

There is some samples how types can be applied:

`import {Components} from '@revolist/revogrid';` - those are component definitions.
`import { RevoGrid } from '@revolist/revogrid/dist/types/interfaces';` - and here you can find types for different entities in grid such as columns etc.

**Comment by LeonardSpencer** [comment]
That will help me, thanks! I tried to use the typescript-file of the wrapper for revogrid (vgrid.ts from the src folder) so I can use the typed version. It throw an exception and I don't know why.

This is my setup. `columns` are a ref to `RevoGrid.ColumnRegular[] ` and `rows` is a ref to `RevoGrid.DataType[]`

```
    <v-grid v-if="rows.length > 0"
      ref="grid"
      resize="true"
      :source="rows" 
      :columns="columns" 
      theme="material"/>
```

This is the error it throws.
```
node_modules/@revolist/vue3-datagrid/src/vue-component-lib/utils.ts:51:41
TS2538: Type 'undefined' cannot be used as an index type.
    49 |   */
    50 |   const Container = defineComponent<Props & InputProps>((props, { attrs, slots, emit }) => {
  > 51 |     let modelPropValue = (props as any)[modelProp];
       |                                         ^^^^^^^^^
    52 |     const containerRef = ref<HTMLElement>();
    53 |     const classes = new Set(getComponentClasses(attrs.class));
    54 |     const onVnodeBeforeMount = (vnode: VNode) => {
```

Any idea?

**Comment by exherb** [comment]
same issue here
