### ISSUE TITLE
How do you include an img source in a cell?

### ISSUE THREAD

**Issue by delebash** [revolist/vue3-datagrid#16]
I have tried it using    cellTemplate: VGridVueTemplate(thumbnail).  However VGridVueTemplate does not seem to be a part of vue3-datagrid.

Or I can manually create the element

 ```
name: 'url',
  prop: 'url',
  cellTemplate: (createElement, props) => {
    return createElement('img', {
    }, props.model[props.prop]);
```

but the source image url is equal to the current prop.  How do I set the img src to equal the url value?

**Comment by j-meds** [comment]
This doesn't seem like a Vue3 Data grid issue. You can probably just create the element and specify the images src.

`let image = createElement("img");
img.src = yourSouce;
return img;`

**Comment by delebash** [comment]
Thanks, I will give it a try.
