### ISSUE TITLE
Custom Editors?

### ISSUE THREAD

**Issue by eslamoo** [revolist/vue3-datagrid#20]
How to define new editors in vue3 syntax because this syntax `const editor = VGridVueEditor(Vue.component("vueEditor", VueEditor));` will not work with vue3 syntax is there any docs or examples for the new version?

**Comment by erod550** [comment]
> I can't think of a usecase where I want to separate out the cell display from a built in editor.

For me I'm building a grid where additional contextual information is displayed in the cell that's based on the amount entered. amount x rate = cost basically. Only the amount can be edited so the editor only displays the changeable amount, but the cell display shows additional info than just the amount.

**Comment by Captain-Justin** [comment]
![image](https://user-images.githubusercontent.com/26615255/207557028-439ca801-5de4-49eb-b7cc-da73fc54e4ae.png)
![image](https://user-images.githubusercontent.com/26615255/207557290-e8e1df2c-180f-4169-ad90-85d0c58fd693.png)
For me，VGridVueEditor is work ,but loses its css.Why,pls

**Comment by revolist** [comment]
All fixed in v4.
