### ISSUE TITLE
Using in component lib?

### ISSUE THREAD

**Issue by ckujawa** [revolist/vue3-datagrid#21]
Hi!

I was wondering if it was possible to use vue3-datagrid as part of a component library? Specifically, I'm trying to wrap it up into a UMD library so I can use it in a Vue app as part of a Java front end (sadly, I can't use straight up Vue). The entry point of my module looks like this:

```
...other imports
import VGrid from '@revolist/vue3-datagrid'

export {...
		VGrid as VGrid}
```
		
and all works until the addition of VGrid. Once I add it in, my browser complains about illegal characters, which points at this in my .umd.js file:

`qt=Mt({À:"A",Á:"A"...`

I did notice that when I build a test project using the grid as part of an app that line contains quotes around the keys as well.  Is what I'm attempting possible? If so, what am I missing? 

Thank you!

-Chris

**Comment by revolist** [comment]
Yes, sure, v4 provides umd and esm packages
