### ISSUE TITLE
when the first input occurs in the grid, the alphabet is always entered regardless of isComposing

### ISSUE THREAD

**Issue by jexycall** [revolist/vue3-datagrid#25]
I have two questions.
This issue is similar to "https://github.com/revolist/revogrid/issues/244"

I am using Korean.
First, when the first input occurs in the grid, the alphabet is always entered regardless of isComposing.
Second, if you press the Tab button in the above situation, it moves to the right twice.

How can I solve the above issue?

Please help.

thank you

https://user-images.githubusercontent.com/23179817/180154067-f41e2597-0262-4690-8982-69649683597a.mp4

**Comment by revolist** [comment]
Should be ok in v4.
