### ISSUE TITLE
The VGrid has initially a height of "0" | Vue3

### ISSUE THREAD

**Issue by BenjaminVockenberg** [revolist/vue3-datagrid#27]
Hello Revolist-Community,

If I install revoGrid for Vue3 as described in your gitReadme, the started Vue3 App does not show anything cause the initial height of the VGrid is set to "0". So you need to give it a height first to see it.

Maybe you should add this info to your Readme. 

Thank you, have a good time and stay healthy

**Comment by revolist** [comment]
Hello @BenjaminVockenberg. Thank you for your feedback.
We will add this information in the 4th version docs.

The main idea behind it to make grid as smart as any element on the page. 
We believe that setting up initial height to the grid itself is old school approach which was popular in old systems but we've tried to make this grid the way so it takes size of any container around it or styles applied to it.
