### ISSUE TITLE
Version 3.2.0 not building

### ISSUE THREAD

**Issue by glennjhicks** [revolist/vue3-datagrid#28]
Since upgrading to version 3.2.0 the code no longer compiles. Missing a dependency to revogrid (custom-element).

![build-error](https://user-images.githubusercontent.com/17492006/184430725-5ab4d8d7-cad0-4ff5-8219-3c17f5ce77e3.JPG)

Sandbox: https://codesandbox.io/s/revo-grid-vue3-forked-h5gz06

You can install the @revolist/revogrid and @stencil/core dependancies to get it working again, but not ideal.
https://codesandbox.io/s/revo-grid-vue3-forked-o0xmru?file=/package.json:228-245

My package.json I am using for a test project (that generated the error in the image)
{
	"name": "revo-test",
	"private": true,
	"version": "0.0.0",
	"type": "module",
	"scripts": {
		"dev": "vite",
		"build": "vite build",
		"preview": "vite preview"
	},
	"dependencies": {
		"@revolist/vue3-datagrid": "^3.2.0",
		"vue": "^3.2.37"
	},
	"devDependencies": {
		"@vitejs/plugin-vue": "^3.0.3",
		"vite": "^3.0.7"
	}
}

**Comment by revolist** [comment]
@glennjhicks thank you very much for adding information (and samples) and posting this issue and possible workarounds. 
We've merged some changes from community and those were conflicting with package.json. Also in the future you could make PR with fix if you wish to support. 

We've been working on Saturday just to close this problem.
Together with it we've built better support for Vite. 
Added Vite working sample:
https://codesandbox.io/s/revogrid-vite-s09mrx

**Comment by m2a2x** [comment]
Hello @DeepBhat 
Thanks for this, very interesting how it was working for me at all.
Updated.
