### ISSUE TITLE
TS7016: Could not find a declaration file for module '@revolist/vue3-datagrid'

### ISSUE THREAD

**Issue by bolerio** [revolist/vue3-datagrid#3]
Hi,

I installed the module as recommended in the docs, trying to incorporate in a new vue3 project. Followed the example to include a simple grid in a vue component, but getting the following error. 

```
TS7016: Could not find a declaration file for module '@revolist/vue3-datagrid'. '/Users/borislav/temp/vuelearn/pitchfor/node_modules/@revolist/vue3-datagrid/dist/vgrid.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/revolist__vue3-datagrid` if it exists or add a new declaration (.d.ts) file containing `declare module '@revolist/vue3-datagrid';`
    14 | <script lang="ts">
    15 | import { ref, defineComponent, onMounted } from 'vue'
  > 16 | import VGrid from '@revolist/vue3-datagrid'
```

There is nothing complicated in my environment, I just used Vue CLI to generate the project scaffolding and then immediately tried using vue3-grid following the docs and hit the above roadblock.

Any suggestion what I could do to solve this?

**Comment by rk87** [comment]
Hi,

I guess when you run `npm run build` and get those error. if YES, you may try to change following line in `package.json`.

`"build": "vue-tsc --noEmit && vite build",` 
1. remove `vue-tsc --noEmit &&` become
`"build": "vite build",`
2. run again `npm run build`

**Comment by UkonnRa** [comment]
Hi, this error still exists in 3.1.0. Any update?

RevoGrid and TypeScript are both amazing tools. Hoping they can work together.


![image](https://user-images.githubusercontent.com/16066720/176370259-1cc45ed3-f7e9-440c-98e0-8424c06c818c.png)

**Comment by revolist** [comment]
Solved
