### ISSUE TITLE
Custom cell element is rendered below the table on overflow

### ISSUE THREAD

**Issue by DeepBhat** [revolist/vue3-datagrid#31]
Hey,

I wanted to implement a tooltip on hover on a custom cell element. The cell contains an image and I wanted to show a bigger size image when hovering on the cell. I successfully implemented a custom cell template, but the tooltip containing the image is rendered below the table, even if I have tried increasing the z-index and set overflow: visible on all cells and columns in the table. 

I am assuming there is a way to display items on top of other cells, but I cannot understand what I am doing wrong.

**Comment by revolist** [comment]
You have to put your tooltip outside of the table 
In other case it's going to be cropped by grid overflow

**Comment by DeepBhat** [comment]
Okay got it. Just to confirm, cropping by grid overflow is intended behavior, right?

**Comment by revolist** [comment]
yes, there is a container with scroll where all cells are. there is overflow for it
