### ISSUE TITLE
Dynamic data support

### ISSUE THREAD

**Issue by piliadis** [revolist/vue3-datagrid#33]
Support dynamic change of data passed into the source prop.
At the current state, if source data changes the data-grid view does not refresh to display it.

Minimal reproduction:
https://codesandbox.io/s/revo-grid-vue3-forked-vdi1pu

**Comment by revolist** [comment]
Hey @piliadis 
thanks for the codesandbox
StencilJs mutation approach is slightly different from original vuejs that is why revo-grid prefers immutable approach.
To make it work in your example:

https://codesandbox.io/s/revo-grid-vue3-forked-nfsvgp

this.rows = [...this.rows, {
        birthdate: "2022-08-26",
        name: "3",
        details: "Item 3",
      }];
