### ISSUE TITLE
o.defineCustomElements is not a function

### ISSUE THREAD

**Issue by guoPengSong** [revolist/vue3-datagrid#36]
Use error in vue3
```
<template>
  <div>
    <v-grid theme="compact" :source="rows" :columns="columns" />
  </div>
</template>

<script>
import VGrid from "@revolist/vue3-datagrid";

export default {
  name: "App",
  data() {
    return {
      columns: [
        {
          prop: "name",
          name: "First",
        },
        {
          prop: "details",
          name: "Second",
        },
      ],
      rows: [
        {
          name: "1",
          details: "Item 1",
        },
      ],
    };
  },
  components: {
    VGrid,
  },
};
</script>
```
<img width="438" alt="image" src="https://user-images.githubusercontent.com/17527334/188275924-488c9b25-d0de-416e-b1ca-22bc5da2b474.png">

**Comment by m2a2x** [comment]
Hello @guoPengSong 
I believe you have newer version of revogrid then was supported by vue3-datagrid

Now it's updated to the latest, you can check it out https://codesandbox.io/s/revo-grid-vue3-thry7?from-embed

**Comment by JavaZWT** [comment]
> Hello @guoPengSong I believe you have newer version of revogrid then was supported by vue3-datagrid
> 
> Now it's updated to the latest, you can check it out https://codesandbox.io/s/revo-grid-vue3-thry7?from-embed

Hi, @m2a2x 

I have the same problem when use the newer version of vue3-datagrid@3.2.6 , and use your demo  vue3-datagrid@3.2.16, it`s ok, but I cannot find  vue3-datagrid@3.2.16 in  [vue3-datagrid releases](https://github.com/revolist/vue3-datagrid/releases?page=1).

When the version of revogrid  updated, can I use the same version in vue3-datagrid ?

**Comment by m2a2x** [comment]
Hey @JavaZWT 
Thank you for the update

Yes, you can use almost any version, except or rare cases like this one.
We've planned to update core bit later in 4+ version but were forced by Svelte framework update

3.2.17 version added, you can see this now in releases

**Comment by JavaZWT** [comment]
@m2a2x  Thank you for your answer!  I will take a look at it!
