### ISSUE TITLE
Filter select condition not working when click by mouse [Firefox]

### ISSUE THREAD

**Issue by bilik-tomas** [revolist/vue3-datagrid#41]
**Describe the issue**
Hello, i notice, when you want to filter column data nothing happends.
I tested it on Edge, there it is working propertly.
On Firefox (110.0.1, Windows) when you choose option from filter conditions by mouse click, nothing happends. If you use enter instead of mouse click, filter works.

**Comment by minu93** [comment]
Ive the same issue

**Comment by revolist** [comment]
Can't reproduce on v4. Please provide codesandbox example.
