### ISSUE TITLE
Drag and drop for custom cellTemplate?

### ISSUE THREAD

**Issue by kylerdong** [revolist/vue3-datagrid#42]
Hi, @revolist . I created my custom cell by using cellTemplate and VGridVueTemplate. 
It lost the drag icon and can not drag and drop anymore. How can enable drag and drop row again?

**Comment by asp-entwickler** [comment]
Hi all,
I started with RevoGrid in Vue 2 project, no custom cell, all out of the box.
Drag control invisible in my case (unable to dragg at all).
Maybe I'm doing something wrong?

**Comment by revolist** [comment]
For custom cells you need to repeat events like they are in original cell render. Or use your own d&d plugin.
