### ISSUE TITLE
Is this actually still supported? Even the most basic stuff doesn't work

### ISSUE THREAD

**Issue by NikiLentz** [revolist/vue3-datagrid#44]
Hi,
I just tried it out and after finally getting it to render in my vue3 project neither resizing the columns, moving them around or adding the predefined date editor for a column works. 

I can't resize it in the revogrid vue demo either. I'll try it without this wrapper now, but imho this should either be massively updated or actually removed as native vue3 support doesn't work at all imho.

**Comment by revolist** [comment]
We've been busy for a while with another project of ours, we've updated project with v4 and full wrappers support.
