### ISSUE TITLE
the data repeats when generate the table.

### ISSUE THREAD

**Issue by eRendon** [revolist/vue3-datagrid#8]
Hi, 

i use

`"@revolist/vue3-datagrid": "^3.0.96",`
`"vue": "^3.0.5",`
`"vite": "^2.4.4",`
`"typescript": "^4.3.5",`

when the table is generate, the data is repeat, in the photo, the colum 'SEXO', repeat at 3 times, but this only happens in production

![image](https://user-images.githubusercontent.com/36104986/131912447-ecbdb4ec-9c07-4d27-b415-1f177d9fecb6.png)

**Comment by revolist** [comment]
Can't reproduce anymore in v4
